ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from userbase.views import ProfileDataView, ProfileUpdateView, CustomerUpdateView, OrderDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/update/', CustomerUpdateView.as_view(),
         name='customer-profile-update'),
    path('accounts/signup/', include('userbase.urls', namespace='signup')),
    path('order/<pk>/', OrderDetailView.as_view(), name='order-detail'),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('cart', views.CartView.as_view(), name='summary'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/seller/<pk>', views.CheckoutView.as_view(), name='checkout'),
    path('payment/checkout/<pk>', views.PaymentView.as_view(), name='payment'),
    path('thanks/payment/<pk>', views.ThankYou.as_view(), name='thanks'),
    path('cart/seller/<pk>', views.CartDetailView.as_view(), name='cart-detail')

]

shop/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from django.utils.text import slugify

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Address(models.Model):
    village = models.CharField(max_length=250)

    def __str__(self):
        return self.village


class Product(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='product_images')
    description = models.TextField()
    price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category, related_name="products")
    owner = models.ForeignKey(
        User, related_name="products", on_delete=models.CASCADE)
    address = models.ManyToManyField(Address, related_name="productaddress")
    available = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product-detail", kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse("staff:product-update", kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse("staff:product-delete", kwargs={'pk': self.pk})

    def get_price(self):
        return self.price

    def get_owner(self):
        return self.owner


class Order(models.Model):
    user = models.ForeignKey(
        User, related_name="orders", on_delete=models.CASCADE, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item()
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="items", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    product_owner = models.ForeignKey(
        User, related_name="items", on_delete=models.CASCADE)
    product_total_price = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.product} x {self.quantity}"

    def get_total_item(self):
        return self.quantity * self.product.price

    def save(self):
        self.product_total_price = self.quantity * self.product.price
        self.product_owner = self.product.owner
        return super(OrderItem, self).save()


class Checkout(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=256, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    request = models.TextField(max_length=256, blank=True, null=True)
    order = models.ForeignKey(
        Order, related_name='checkout', on_delete=models.CASCADE)
    owner = models.ForeignKey(
        User, related_name="checkoutowner", on_delete=models.CASCADE, blank=True, null=True)
    totalpay = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    checkout_date = models.DateTimeField(
        auto_now_add=True, blank=True, null=True)
    user = models.ForeignKey(
        User, related_name="checkoutuser", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.reference_number

    def save(self):
        super(Checkout, self).save()
        objs = [
            RealOrderItem(
                checkout=Checkout.objects.get(id=self.id),
                order=self.order,
                product=item.product,
                quantity=item.quantity,
                product_owner=item.product_owner,
                product_total_price=item.product_total_price
            )
            for item in self.order.items.filter(order__checkout__pk=self.id, order=self.order, product_owner=self.owner)
        ]
        if self.status == False:
            RealOrderItem.objects.bulk_create(objs)

    @property
    def reference_number(self):
        return f"CHECKOUT-{self.pk}"


class RealOrderItem(models.Model):
    checkout = models.ForeignKey(
        Checkout, related_name="real", on_delete=models.CASCADE)
    order = models.ForeignKey(
        Order, related_name='orders', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="products", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    product_owner = models.ForeignKey(
        User, related_name="owners", on_delete=models.CASCADE,)
    product_total_price = models.IntegerField(default=0)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"ITEM-{self.pk} {self.product.title} X {self.quantity} - {self.checkout}"


class Payment(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='payments')
    timestamp = models.DateTimeField(auto_now_add=True)
    receipt = models.FileField(
        upload_to='payment_receipt', blank=True, null=True)
    owner = models.ForeignKey(
        User, related_name="paymentowner", on_delete=models.CASCADE, blank=True, null=True)
    checkout = models.ForeignKey(
        Checkout, related_name="paymentcheckout", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"PAYMENT-{self.pk} - {self.checkout}"


def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


pre_save.connect(pre_save_product_receiver, sender=Product)

shop/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import (
    OrderItem, Product, Checkout, Payment, Order
)

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = OrderItem
        fields = ['quantity', ]

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

    def clean(self):
        product_id = self.product_id
        product = Product.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = [
            'address',
            'request',
        ]


class PaymentForm(forms.ModelForm):
    receipt = forms.FileField(label='receipt', required=True)

    class Meta:
        model = Payment
        fields = [
            'receipt'
        ]

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views import generic
from .forms import AddToCartForm, AddressForm, PaymentForm
from .models import Product, OrderItem, Payment, Order, Category, Checkout
from .utils import get_or_set_order_session
from .filters import ProductFilter
from django.db.models import Count, Sum
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings

User = get_user_model()


class ProductDetailView(generic.FormView):
    template_name = 'shop/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("shop:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product
        )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(LoginRequiredMixin, generic.TemplateView):
    template_name = "shop/cart.html"

    def get_queryset(self):
        order = get_or_set_order_session(self.request)
        return order

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        cart = self.get_queryset()
        context["order"] = cart.items.values(
            'product_owner__name', 'product_owner').annotate(count=Count('product_owner__name'), countpro=Sum('quantity'))
        return context


class CartDetailView(generic.TemplateView):
    template_name = "shop/cart-detail.html"

    def get_queryset(self):
        order = get_or_set_order_session(self.request)
        return order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.get_queryset()

        context["orderitem"] = cart.items.filter(
            product_owner=self.kwargs['pk'])
        context["total"] = cart.items.filter(
            product_owner=self.kwargs['pk']).aggregate(price=Sum('product_total_price'))
        context['kwargs'] = self.kwargs
        return context


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.product_total_price += order_item.product.price
        order_item.save()
        return redirect("shop:summary")


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.product_total_price -= order_item.product.price
            order_item.save()
        return redirect("shop:summary")


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("shop:summary")


class CheckoutView(LoginRequiredMixin, generic.FormView):
    template_name = 'shop/checkout.html'
    form_class = AddressForm

    def get_queryset(self):
        order = get_or_set_order_session(self.request)
        return order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.get_queryset()
        context["orderitem"] = cart.items.filter(
            product_owner=self.kwargs['pk'])
        context["total"] = cart.items.filter(
            product_owner=self.kwargs['pk']).aggregate(price=Sum('product_total_price'))
        context['kwargs'] = self.kwargs
        return context

    def form_valid(self, form):
        carts = self.get_queryset()
        total = carts.items.filter(
            product_owner__id=self.kwargs['pk']).aggregate(price=Sum('product_total_price'))
        obj = form.save(commit=False)
        obj.order = get_or_set_order_session(self.request)
        obj.name = self.request.user.name
        obj.phone = self.request.user.phone
        obj.owner = User.objects.get(pk=self.kwargs['pk'])
        obj.totalpay = total['price']
        obj.user = User.objects.get(pk=self.request.user.pk)
        obj.save()

        self.pk = obj.pk

        shopemail = User.objects.filter(checkoutowner__pk=self.pk)
        order = Checkout.objects.get(pk=self.pk)
        username = self.request.user.name
        useremail = self.request.user.email

        full_message = f"""
            Hi, You just have new order from

            user = {username}
            email = {useremail}

            with order code {order}, please check your order.

            Have a great day.

            """

        for i in shopemail:
            send_mail(
                subject="SIUSADA - New Order",
                message=full_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[i.email]
            )

        return super(CheckoutView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse("shop:payment", kwargs={'pk': self.pk})


class PaymentView(LoginRequiredMixin, generic.FormView):
    template_name = 'shop/payment.html'
    form_class = PaymentForm

    def get_queryset(self):
        order = get_or_set_order_session(self.request)
        return order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.get_queryset()
        context["total"] = Checkout.objects.filter(pk=self.kwargs['pk'])
        context['kwargs'] = self.kwargs
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.order = get_or_set_order_session(self.request)
        obj.owner = User.objects.get(checkoutowner__pk=self.kwargs['pk'])
        obj.checkout = Checkout.objects.get(pk=self.kwargs['pk'])
        obj.save()
        self.pk = obj.pk
        return super(PaymentView, self).form_valid(form)

    def get_success_url(self):
        return reverse("shop:thanks", kwargs={'pk': self.pk})


class ThankYou(generic.TemplateView):
    template_name = 'shop/thanks.html'

templates/shop/cart-detail.html
{% extends "base.html" %}

{% block head_title %}Cart Detail{% endblock %}
{% block content %}


<div class="bg-white fixed-top border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <a class="card-link" href="{% url 'shop:summary' %}">Cart</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Cart Detail</strong>
            </div>
        </div>
    </div>
</div>



<div class="container py-3" style="margin-top: 80px">

    {% for item in orderitem %}
    <div class="card p-3 mb-3">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ item.product.image.url }}" class="img-fluid rounded border">
            </div>
            <div class="col-md-6">
                <div class="card table-responsive p-3">
                    <h2 class="h4 text-black">{{ item.product.title }}</h2>
                    <table class="table mt-1">
                        <tr>
                            <td><strong>Price</strong></td>
                            <td>:</td>
                            <td></strong> Rp{{ item.product.get_price }}</td>
                        </tr>
                        <tr>
                            <td><strong>Quantity</strong></td>
                            <td>:</td>
                            <td>
                                <div class="input-group" style="max-width: 120px;">
                                    <div class="input-group-prepend">
                                        <a href="{% url 'shop:decrease-quantity' item.id %}"
                                            class="btn btn-outline-primary">
                                            &minus;
                                        </a>
                                    </div>
                                    <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                    <div class="input-group-append">
                                        <a href="{% url 'shop:increase-quantity' item.id %} "
                                            class="btn btn-outline-primary">
                                            &plus;
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><strong>Total</strong></td>
                            <td>:</td>
                            <td>
                                Rp{{ item.get_total_item }}
                            </td>
                        </tr>
                    </table>
                    <a href="{% url 'shop:remove-from-cart' item.id %}" class="btn btn-danger">Remove</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="card p-3 mt-5">
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-outline-primary btn-block mb-3" href="{% url 'home' %}">Continue
                    shopping</a>
            </div>
            <div class="col-md-6">
                <div class="card p-3">
                    <h3 class="text-black text-uppercase">Cart Totals</h3>
                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <td>Total</td>
                                <td>:</td>
                                <td>Rp{{ total.price }}</td>
                            </tr>
                        </table>
                    </div>
                    <a class="btn btn-primary btn-block" href="{% url 'shop:checkout' kwargs.pk %}">Proceed to
                        checkout</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content%}

templates/shop/cart.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Cart{% endblock %}
{% block content %}


<div class="bg-white fixed-top border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Cart</strong>
            </div>
        </div>
    </div>
</div>



<div class="container py-3" style="margin-top: 80px">

    {% if order.count > 0 %}

    <div class="card p-3">
        <div class="alert alert-success"> <i class="fas fa-info-circle mr-3"></i> Use the 'Checkout' button to see your
            product and check them out.</div>
        <div class="card p-2 mb-2">
            <div class="table-responsive">
                <table class="table table-borderless">
                    <tr>
                        <th>Shop</th>
                        <th>Product</th>
                        <th>Item</th>
                        <th>Action</th>
                    </tr>

                    {% for item in order %}

                    <tr>
                        <td>{{item.product_owner__name}}</td>
                        <td>{{item.count}}</td>
                        <td>{{item.countpro}}</td>
                        <td>
                            <a class="btn btn-primary"
                                href=" {% url 'shop:cart-detail' item.product_owner %} ">Checkout</a>
                        </td>
                    </tr>

                    {% endfor %}

                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 my-3">
                <a class="btn btn-outline-primary btn-block" href="{% url 'home' %}">Continue
                    shopping</a>
            </div>
        </div>
    </div>
    {% else %}
    <div class="card p-3">
        There are no items in your cart.
        <a class="my-3 card-link" href="{% url 'home' %}">Continue shopping</a>
    </div>
    {% endif %}
</div>


{% endblock content %}

templates/shop/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Checkout{% endblock %}
{% block content %}

<div class="bg-white border-bottom fixed-top py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a><span class="mx-2 mb-0">/</span>
                <a class="card-link" href="{% url 'shop:summary' %}">Cart</a><span class="mx-2 mb-0">/</span>
                <strong class="text-black">Checkout</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">

    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 mb-5">
                <div class="card p-3">
                    <h2 class="h3 mb-3 text-black text-center">Billing Details</h2>
                    <hr />
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"
                            href="{% url 'shop:payment' kwargs.pk %}">Proceed to
                            payment</button>
                    </div>

                </div>
            </div>
            <div class="col-md-6 mb-5">
                <div class="card p-3">
                    <h2 class="h3 text-black text-center">Your Order</h2>
                    <div class="card p-3 my-3">
                        <strong class="mb-3">Summary</strong>
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total Price</th>
                                </tr>
                                {% for item in orderitem %}
                                <tr>
                                    <td>{{ item.product.title }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>Rp{{ item.get_total_item }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <div class="card p-3">
                        <strong class="mb-3">Total</strong>
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th>Order Total</th>
                                    <td>:</td>
                                    <td><strong class="text-black">
                                            Rp {{total.price}}
                                        </strong></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    </form>

</div>

{% endblock content %}

templates/shop/payment.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block head_title %}Payment{% endblock %}
{% block content %}

<div class="bg-white border-bottom fixed-top py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a><span class="mx-2 mb-0">/</span>
                <a class="card-link" href="{% url 'shop:summary' %}" class="text-black">Cart</a><span
                    class="mx-2 mb-0">/</span>
                <strong class="text-black">Payments</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">
    <div class="row justify-content-center">
        <div class="col-md-6 my-5">
            <div class="card p-3">

                <div class="card p-3">
                    <strong class="my-3">Payment Address</strong>
                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>Address</th>
                                <th>Number</th>
                                <th>Name</th>
                            </tr>

                            <tr>
                                <td>Dana</td>
                                <td>1234567890</td>
                                <td>SIUSADA</td>
                            </tr>
                            <tr>
                                <td>OVO</td>
                                <td>1234567890</td>
                                <td>SIUSADA</td>
                            </tr>

                        </table>
                    </div>
                </div>

                <div class="alert alert-primary my-3"><strong>Order total: Rp
                        {% for t in total %}{{t.totalpay}}{% endfor %}</strong></div>

                <div class="card p-3 my-3">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-primary btn-block"
                            href="{% url 'shop:thanks' kwargs.pk %}">Finish Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/shop/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Product Detail{% endblock %}
{% block content %}

<div class="bg-white fixed-top border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong>{{product.owner.name}}</strong>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">
    <div class="row mb-5">
        <div class="col-md-6 mb-3">
            <img src="{{ product.image.url }}" class="img-fluid rounded">
            {% if request.user.is_authenticated and not request.user.is_staff %}
            <div class="card p-3 my-3">
                {% if product.available == True %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class="btn btn-primary float-right">Add to cart</button>
                </form>
                {% endif %}</div>
            {% endif %}
        </div>
        <div class="col-md-6">
            <div class="card p-3">
                <h2 class="text-black">{{ product.title }}</h2>
                <hr>
                <h5><span class="badge badge-success">Rp {{ product.price }}</span></h5>
                <strong class="my-3 alert alert-success p-3 text-center">
                    <a class="card-link" href="https://api.whatsapp.com/send?phone={{product.owner.phone}}"><i
                            class="fab fa-whatsapp font-weight-bold mr-2"></i> Chat on
                        Whatsapp</a>
                </strong>
                <div class="alert alert-secondary">
                    <h5>Description</h5>
                    <hr>
                    <p>{{ product.description }}</p>
                </div>

                <div class="alert alert-secondary">
                    <h5>Status</h5>
                    <hr>
                    <p>{% if product.available == True %} This product is available {% else %} This product is currently
                        not available
                        {% endif %}</p>
                </div>

            </div>
        </div>
    </div>
</div>


{% endblock content %}