ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from userbase.views import ProfileDataView, ProfileUpdateView, CustomerUpdateView, OrderDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/update/', CustomerUpdateView.as_view(),
         name='customer-profile-update'),
    path('accounts/signup/', include('userbase.urls', namespace='signup')),
    path('order/<pk>/', OrderDetailView.as_view(), name='order-detail'),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('cart', views.CartView.as_view(), name='summary'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/seller/<pk>', views.CheckoutView.as_view(), name='checkout'),
    path('payment/checkout/<pk>', views.PaymentView.as_view(), name='payment'),
    path('thanks/payment/<pk>', views.ThankYou.as_view(), name='thanks'),
    path('cart/seller/<pk>', views.CartDetailView.as_view(), name='cart-detail')

]

userbase/urls.py
from . import views
from django.urls import path

app_name = 'userbase'

urlpatterns = [
    path('vendor', views.StaffSignup.as_view(),
         name='staff-sign-up'),
    path('customer', views.CustomerSignup.as_view(),
         name='customer-sign-up')
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>SIUSADA - {% block head_title %}Lapaknya UMKM Nusa Penida{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'icons/siusada.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href=" {% static 'fonts/fontawesome/css/all.min.css' %}" />
</head>

<body>

    {% block content %}

    {% endblock content %}


    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Contact{% endblock %}

{% block content %}

<div class="bg-white fixed-top border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card p-3">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>

                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}

                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-block mt-3" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/footer.html
<footer class="border-top py-3" style="background-color: #435979">
    <div class="container pb-5">
        <div class="text-center pb-3">
            <p>
                <p class="text-white">
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    SIUSADA. All rights reserved
                </p>
                <span>
                    {% if not request.user.is_authenticated %}
                    <a class="btn btn-success" href=" {% url 'signup:staff-sign-up' %} ">Become a Vendor</a>
                    <span class="mx-3">|</span>
                    {% endif %}
                    <a class="btn btn-outline-success" href=" {% url 'contact' %} ">Contact Us</a>
                </span>
            </p>
        </div>
    </div>
</footer>

templates/order-detail.html
{% extends "base.html" %}

{% block head_title %}Order Detail{% endblock %}
{% block content %}

<div class="bg-white fixed-top border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <a class="card-link" href="{% url 'profile' %}">Profile</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Order Details</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">
    <div class="card p-3">
        <h5 class="card-title">
            Checkout: {% for item in order %}{{item.reference_number}}{% endfor %}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">Checkout on: {% for item in order %}{{item.checkout_date}}{% endfor %}
        </h6>

        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
                {% for item in order %}
                {% for i in item.real.all %}
                <tr>
                    <td>{{ i.product.title }}</td>
                    <td>{{i.product.price}}</td>
                    <td>{{ i.quantity }}</td>
                    <td>Rp{{ i.product_total_price }}</td>
                </tr>
                {% endfor %}
                <tr class="alert-primary">
                    <td>Total</td>
                    <td></td>
                    <td></td>
                    <td>Rp{{ item.totalpay }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/profile-update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Profile Update Form{% endblock %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <a class="card-link" href="{% url 'profile' %}">Profile</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Profile Update Form</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section my-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card p-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            Your Profile
                        </h5>

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type='submit' class='btn btn-primary float-right'>Update</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/topbar.html
{% load crispy_forms_tags %}
{% load static %}
{% load cart_template_tags %}

<div class="d-inline-flex flex-row card px-3 pt-3 pb-2 rounded-0 bg-white fixed-top border-bottom">
	<a class="mr-auto" href="/">
		<img src=" {% static 'icons/siusadatext.png' %} " width="auto" height="35" class="d-inline-block"
			alt="Siusada" />
	</a>

	<div class="d-none d-sm-block d-md-none d-lg-block">
		<form method="GET" class="mx-3">
			<div class="row">
				<div class="col-md-7">
					<span>{{ filter.form.title|as_crispy_field }}</span>
					<span hidden>{{ filter.form.category|as_crispy_field }}</span>
					<span hidden>{{ filter.form.address|as_crispy_field }}</span>
				</div>

				<div class="col-md-2">
					<button class="btn btn-outline-primary">
						Search
					</button>
				</div>

				<div class="col-md-3">
					{% if not request.user.is_staff %}
					<a class="btn" href="{% url 'shop:summary' %}">
						<span class="alert alert-success p-2">
							<span><i class="fas fa-shopping-cart"></i> {{ request|cart_item_count }}</span>
						</span>
					</a>
					{% endif %}
				</div>
			</div>

		</form>
	</div>


	{% if request.user.is_authenticated and not request.user.is_superuser %}

	<div class="ml-auto">
		<a class="btn mr-1"
			href=" {% if request.user.is_staff %} {% url 'staff:profile' %} {% else %} {% url 'profile' %} {% endif %}">
			{% if user.avatar %}
			<img src=" {{user.avatar.url}} " width="30" height="30" class="rounded-avatar" alt="{{user.name}}" />
			{% endif %} Profile
		</a>
		<a class="btn btn-outline-primary" href=" {% url 'account_logout' %} ">Log out</a>
	</div>

	{% else %}
	<div class="ml-auto">
		<a class="btn btn-outline-primary mr-1" href="{% url 'account_login' %}">Login</a>
		<a class="btn btn-primary" href="{% url 'signup:customer-sign-up' %}">Register</a>
	</div>
	{% endif %}

</div>

{% if messages %}
{% for message in messages %}
<div class="container fixed-top" style="margin-top:100px">
	<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
		<span class="alert-inner--text">{{ message }}</span>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
</div>
{% endfor %}
{% endif %}

templates/userprofile.html
{% extends "base.html" %}

{% block head_title %}Profile{% endblock %}
{% block content %}

<div class="bg-white border-bottom fixed-top py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a class="card-link" href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Profile</strong>
            </div>
        </div>
    </div>
</div>


<div class="container" style="margin-top: 80px">
    <div class="card p-3">
        <h3 class="mb-3">Hi, {{user.name}} !!</h3>
        <hr>
        <form>
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="card p-3 mb-3">
                        <div class="text-center">
                            {% if user.avatar %}
                            <img alt="{{user.name}}" src="{{user.avatar.url}}" class="rounded border" width="128"
                                height="128" />
                            {% endif %}
                            <h2 class="my-3"> {{user.name}} </h2>
                            <a href=" {% url 'customer-profile-update' pk=request.user.id %} "
                                class="btn btn-primary my-2">Update
                                Profile</a>
                            <br>
                            <a href="{% url 'account_change_password' %}" class="btn btn-primary my-2">
                                Update Password
                            </a>
                            <br>
                            <a class="btn btn-outline-primary my-2" href="{% url 'account_logout' %}">
                                Log out
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card p-3">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" value="{{user.name}}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" value="{{user.email}}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input class="form-control" id="phone" value="{{user.phone}}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" value="{{user.user_address}}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="bio">Biography</label>
                            <input type="text" class="form-control" id="bio" value=" {{user.biography}} " disabled>
                            </input>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>


    <div class="card p-3 my-3">
        <h5 class="card-title">
            Your Order
        </h5>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Reference No.</td>
                    <th>Date</td>
                    <th>Amount</td>
                    <th>Status</th>
                </tr>
                {% for order in object_list %}

                <tr>
                    <td><a class="card-link" href="{% url 'order-detail' order.pk %}">#{{ order.reference_number }}</a>
                    </td>
                    <td>{{ order.checkout_date }}</td>
                    <td>Rp{{ order.totalpay }}</td>
                    <td>{% if order.status == False %}Unconfirmed {% else %} Confirmed {% endif %}</td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan="4">You haven't made any orders</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <hr>
        <nav class="ml-auto" aria-label="Page navigation example">
            <ul class="pagination p-3">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                {% endif %}

                {%for i in paginator.page_range%}

                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                    <a class="page-link" href="?page={{i}}">{{i}}</a>
                </li>
                {%endfor%}

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                        href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item"><a class="page-link"
                        href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock content %}