ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from userbase.views import ProfileDataView, ProfileUpdateView, CustomerUpdateView, OrderDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/update/', CustomerUpdateView.as_view(),
         name='customer-profile-update'),
    path('accounts/signup/', include('userbase.urls', namespace='signup')),
    path('order/<pk>/', OrderDetailView.as_view(), name='order-detail'),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views
from userbase.views import ProfileDataView, ProfileUpdateView

app_name = 'staff'

urlpatterns = [
    path('', views.StaffBaseView.as_view(), name='dashboard'),
    path('profile/', ProfileDataView.as_view(), name='profile'),
    path('profile/<pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<pk>/update/',
         views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/',
         views.ProductDeleteView.as_view(), name='product-delete'),
    path('order/', views.StaffOrderView.as_view(), name='order'),
    path('order/confirmed', views.ConfirmedOrderView.as_view(),
         name='confirmed-order'),
    path('order/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('order/<pk>/confirm-order/',
         views.ConfirmOrderView.as_view(), name='confirm-order'),
]

templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Web UI Kit &amp; Dashboard Template based on Bootstrap">
    <meta name="author" content="SIUSADA">
    <meta name="keywords" content="adminkit, bootstrap, web ui kit, dashboard template, admin template">

    <link rel="shortcut icon" href=" {% static 'icons/siusada.png' %} " />

    <title>SIUSADA - Dashboard</title>

    <link href=" {% static 'dashboard/css/app.css' %} " rel="stylesheet">
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/dashboard/confirm.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}



<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Order Confirmation</h1>
					<div class="w-100">
						<div class="card">

							<div class="card-body">
								<h5 class="card-title">
									Checkout:
									{% for i in checkouts %}{{i.reference_number}}{% endfor %}
								</h5>
								<div class="alert alert-primary p-3">Please check the 'Status' to confirm your
									customer order</div>
								<form method="post">
									{% csrf_token %}
									{{form|crispy}}
									<button class="btn btn-primary" type="submit">Confirm</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/confirmed-order.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content %}



<div class="wrapper">
    {% include 'dashboard/sidebar.html' %}
    <div class="main">
        {% include 'dashboard/navbar.html' %}
        <main class="content">
            <div class="container-fluid p-0">
                <div class="row">
                    <h1 class="h3 mb-3">Confirmed Orders</h1>
                    <div class="w-100">
                        <div class="card">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Reference No.</th>
                                            <th>Date</th>
                                            <th>Customer</th>
                                            <th>Amount</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for orderx in object_list %}
                                        <tr>
                                            <td>
                                                <a class="card-link" href="{% url 'staff:order-detail' orderx.pk %}">
                                                    #{{orderx.reference_number}}
                                                </a>
                                            </td>
                                            <td>{{ orderx.checkout_date }}</td>
                                            <td>{{ orderx.user.email }}</td>
                                            <td>Rp {{orderx.totalpay}} </td>
                                            <td> {% if orderx.status == False %}Unconfirmed {% else %} Confirmed
                                                {% endif %} </td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="4">
                                                You don't have any order yet
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <hr>
                            <nav class="ml-auto" aria-label="Page navigation example">
                                <ul class="pagination p-3">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                            href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                                    {% endif %}

                                    {%for i in paginator.page_range%}

                                    <li class="page-item {% if page_obj.number == i %}active
                    {% endif %}">
                                        <a class="page-link" href="?page={{i}}">{{i}}</a>
                                    </li>
                                    {%endfor%}

                                    {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link"
                                            href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Next</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                            href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">Last</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% include 'dashboard/footer.html' %}
    </div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="d-flex text-muted">
            <div class="ml-auto">
                <p class="mb-0">
                    <a href=" {% url 'staff:dashboard' %} " class="text-muted card-link"><strong>SIUSADA</strong></a>
                    &copy;
                    <strong>
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                    </strong>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/dashboard/index.html
{% extends 'dashboard/base.html' %} {% load static %} {% block content %}

<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Dashboard</h1>
					<div class="w-100">
						<div class="row">
							<div class="col-sm-6">
								<div class="card" style="background-color: #d6adff">
									<div class="card-body d-flex">
										<span>
											<h5 class="card-title mb-4">
												Item Solds
											</h5>
											<h1 class="display-5 mt-1 mb-3 font-weight-bold">
												{% if solds.total is not None %}
												{{solds.total}}
												{% else %}
												0
												{% endif %}
											</h1>
										</span>
										<span class="ml-auto">
											<i class="fas fa-3x fa-user" style="color: #ecd9ff"></i>
										</span>
									</div>
								</div>
								<div class="card" style="background-color: #8affc2">
									<div class="card-body d-flex">
										<span>
											<h5 class="card-title mb-4">
												Products
											</h5>
											<h1 class="display-5 mt-1 mb-3 font-weight-bold">
												{{products}}
											</h1>
										</span>
										<span class="ml-auto">
											<i class="fas fa-3x fa-shopping-bag" style="color: #ccffe4"></i>
										</span>
									</div>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="card" style="background-color: #ffd357">
									<div class="card-body d-flex">
										<span>
											<h5 class="card-title mb-4">
												Earnings (Rp)
											</h5>
											<h1 class="display-5 mt-1 mb-3 font-weight-bold">
												{% if earnings.earn is not None %}
												{{earnings.earn}}
												{% else %}
												0
												{% endif %}
											</h1>
										</span>
										<span class="ml-auto">
											<i class="fas fa-3x fa-money-bill" style="color: #fff5d9"></i>
										</span>
									</div>
								</div>
								<div class="card" style="background-color: #94c6ff">
									<div class="card-body d-flex">
										<span>
											<h5 class="card-title mb-4">
												Orders
											</h5>
											<h1 class="display-5 mt-1 mb-3 font-weight-bold">
												{{order}}
											</h1>
										</span>
										<span class="ml-auto">
											<i class="fas fa-3x fa-shopping-cart" style="color: #dbecff"></i>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="card flex-fill">
						<div class="card-header">
							<h5 class="card-title mb-0">Recent Orders</h5>
						</div>
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>Reference No.</th>
										<th>Date</th>
										<th>Customer</th>
										<th>Amount</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>

									{% for orderx in recents %}
									<tr>
										<td>
											<a class="card-link" href="{% url 'staff:order-detail' orderx.pk %}">
												#{{orderx.reference_number}}
											</a>
										</td>
										<td>{{ orderx.checkout_date }}</td>
										<td>{{ orderx.user.email }}</td>
										<td>Rp {{orderx.totalpay}} </td>
										<td> {% if orderx.status == False %}Unconfirmed {% else %} Confirmed
											{% endif %} </td>
									</tr>
									{% empty %}
									<tr>
										<td colspan="4">
											You don't have any order yet
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>

<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/navbar.html
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle d-flex">
        <i class="hamburger align-self-center"></i>
    </a>

    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                    <i class="align-middle" data-feather="settings"></i>
                </a>

                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                    {% if user.avatar %}
                    <img src=" {{user.avatar.url}} " class="avatar img-fluid rounded mr-1" alt="{{user.name}}" />
                    {% endif %}
                    <span class="text-dark">{{user.name}}</span>

                </a>
                {% endif %}
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href=" {% url 'staff:profile' %} "><i class="align-middle mr-1"
                            data-feather="user"></i>
                        Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href=" {% url 'account_logout' %} "><i class="align-middle mr-1"
                            data-feather="power"></i> Log out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/dashboard/order-detail.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}



<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Order Detail</h1>
					<div class="w-100">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">
									Checkout:
									{% for i in checkouts %}{{i.reference_number}}{% endfor %}
								</h5>
								<h6 class="card-subtitle mb-2 text-muted">Checkout on:
									{% for i in checkouts %}{{i.checkout_date}}{% endfor %}</h6>

								{% for i in checkouts %}
								<a class="btn btn-primary my-3 card-link"
									href=" {% url 'staff:confirm-order' i.pk %} ">Confirm
									Order</a>
								{% endfor %}
								<div class="my-3">
									<h5 class="card-title pt-3">
										Items
									</h5>
								</div>
								<div class="table-responsive">
									<table class="table">
										<tr>
											<th>Product</th>
											<th>Price</th>
											<th>Quantity</th>
											<th>Total</th>
										</tr>

										{% for items in itemcheckout %}
										{% for item in items.real.all %}
										<tr>
											<td>{{ item.product.title }}</td>
											<td>Rp{{ item.product.price }}</td>
											<td>{{ item.quantity }}</td>
											<td>Rp{{ item.product_total_price }}</td>
										</tr>
										{% endfor %}
										{% endfor %}
									</table>
									<div class="btn btn-outline-primary disabled">
										<h6 class="my-2">Total amount:
											{% for i in checkouts %}{{i.totalpay}}{% endfor %}</h6>
									</div>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="card-body">
								<div class="card-title">
									<h5 class="card-title">
										Extra Order Data
									</h5>
									<div class="table-responsive">
										<table class="table">
											<tr>
												<th>Name</th>
												<th>Phone</th>
												<th>Address</th>
												<th>Request</th>
												<th>Status</th>
											</tr>
											{% for item in customers %}
											<tr>
												<td> {{item.name}} </td>
												<td> {{item.phone}} </td>
												<td> {{item.address}} </td>
												<td> {{item.request}} </td>
												<td> {% if item.status == False %}Unconfirmed {% else %} Confirmed
													{% endif %} </td>
											</tr>
											{% endfor %}
										</table>
									</div>
								</div>
							</div>
						</div>

						<div class="card">
							<div class="card-body">
								<div class="card-title">
									<h5 class="card-title">
										Payment Data
									</h5>
									<div class="table-responsive">
										<table class="table">
											<thead>
												<tr>
													<th>Time</th>
													<th>Payment Receipt</th>
												</tr>
											</thead>
											<tbody>
												{% for item in payments %}
												<tr>
													<td> {{item.timestamp}} </td>
													<td><a href="{{item.receipt.url}}">View File</a></td>
												</tr>
												{%empty%}
												<tr>
													<td> No payment data </td>
												</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/order.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content %}



<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Orders</h1>
					<div class="w-100">
						<div class="card">
							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>Reference No.</th>
											<th>Date</th>
											<th>Customer</th>
											<th>Amount</th>
											<th>Status</th>
										</tr>
									</thead>
									<tbody>
										{% for orderx in object_list %}
										<tr>
											<td>
												<a class="card-link" href="{% url 'staff:order-detail' orderx.pk %}">
													#{{orderx.reference_number}}
												</a>
											</td>
											<td>{{ orderx.checkout_date }}</td>
											<td>{{ orderx.user.email }}</td>
											<td>Rp {{orderx.totalpay}} </td>
											<td> {% if orderx.status == False %}Unconfirmed {% else %} Confirmed
												{% endif %} </td>
										</tr>
										{% empty %}
										<tr>
											<td colspan="4">
												You don't have any order yet
											</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							<hr>
							<nav class="ml-auto" aria-label="Page navigation example">
								<ul class="pagination p-3">
									{% if page_obj.has_previous %}
									<li class="page-item"><a class="page-link"
											href="?page={{ page_obj.previous_page_number }}">Previous</a>
									</li>
									<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
									{% endif %}

									{%for i in paginator.page_range%}

									<li class="page-item {% if page_obj.number == i %}active{% endif %}">
										<a class="page-link" href="?page={{i}}">{{i}}</a>
									</li>
									{%endfor%}

									{% if page_obj.has_next %}
									<li class="page-item"><a class="page-link"
											href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Next</a>
									</li>
									<li class="page-item"><a class="page-link"
											href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">Last</a>
									</li>
									{% endif %}
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/product-create.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Create Product</h1>
					<div class="w-100">
						<div class="card">
							<div class="card-body">
								<form method="POST" enctype="multipart/form-data">
									{% csrf_token %}
									{{ form|crispy }}
									<button type='submit' class='btn btn-primary'>Save</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/product-update.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Update Product</h1>
					<div class="w-100">
						<div class="card">
							<div class="card-body">
								<form method="POST" enctype="multipart/form-data">
									{% csrf_token %}
									{{ form|crispy }}
									<button type='submit' class='btn btn-primary'>Update</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/product.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content %}



<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">
			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Products</h1>
					<div class="ml-auto text-right mt-n1">
						<nav aria-label="breadcrumb">
							<a class="btn btn-primary card-link" href="{% url 'staff:product-create' %}">Create
								Product</a>
						</nav>
					</div>

					<div class="w-100">
						<div class="card">
							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>Title</th>
											<th>Price</th>
											<th>Category</th>
											<th>Status</th>
											<th>Edit</th>
											<th>Delete</th>
										</tr>
									</thead>
									<tbody>
										{% for product in object_list %}
										<tr>
											<td>{{product.title}}</td>
											<td>{{product.price}}</td>
											<td>{% for list in product.category.all %}
												<span class="badge badge-secondary">{{list}} </span>
												{% endfor %}
											</td>
											<td>{% if product.available == True %}Available {% else %} Not
												Available{% endif %}</td>
											<td class="table-action">
												<a href=" {{product.get_update_url}} " class="mx-3 card-link">
													<i class="align-middle" data-feather="edit-2">
													</i>
												</a>
											</td>
											<td>
												<a href=" {{ product.get_delete_url }} " class="mx-3 card-link">
													<i class="align-middle" data-feather="trash">
													</i>
												</a>
											</td>
										</tr>

										{% empty %}
										<tr>
											<td colspan="4">
												You don't have any product yet
											</td>
										</tr>
										{% endfor %}

									</tbody>

								</table>
							</div>
							<hr>
							<nav class="ml-auto" aria-label="Page navigation example">
								<ul class="pagination p-3">
									{% if page_obj.has_previous %}
									<li class="page-item"><a class="page-link"
											href="?page={{ page_obj.previous_page_number }}">Previous</a>
									</li>
									<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
									{% endif %}

									{%for i in paginator.page_range%}

									<li class="page-item {% if page_obj.number == i %}active{% endif %}">
										<a class="page-link" href="?page={{i}}">{{i}}</a>
									</li>

									{%endfor%}

									{% if page_obj.has_next %}
									<li class="page-item"><a class="page-link"
											href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Next</a>
									</li>
									<li class="page-item"><a class="page-link"
											href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">Last</a>
									</li>
									{% endif %}
								</ul>
							</nav>

						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content %}


<div class="wrapper">
	{% include 'dashboard/sidebar.html' %}
	<div class="main">
		{% include 'dashboard/navbar.html' %}
		<main class="content">

			<div class="container-fluid p-0">
				<div class="row">
					<h1 class="h3 mb-3">Your Profile</h1>
					<div class="w-100">
						<div class="card">
							<div class="card-body">
								<form>
									<div class="row">
										<div class="col-md-8">
											<div class="form-group">
												<label for="name">Name</label>
												<input type="text" class="form-control" id="name" value="{{user.name}}"
													disabled>
											</div>
											<div class="form-group">
												<label for="email">Email</label>
												<input type="email" class="form-control" id="email"
													value="{{user.email}}" disabled>
											</div>
											<div class="form-group">
												<label for="phone">Phone</label>
												<input class="form-control" id="phone" value="{{user.phone}}" disabled>
											</div>
											<div class="form-group">
												<label for="address">Address</label>
												<input type="text" class="form-control" id="address"
													value="{{user.user_address}}" disabled>
											</div>
											<div class="form-group">
												<label for="bio">Biography</label>
												<input type="text" class="form-control" id="bio"
													value=" {{user.biography}} " disabled>
												</input>
											</div>
										</div>
										<div class="col-md-4">
											<div class="text-center">
												{% if user.avatar %}
												<img alt="{{user.name}}" src="{{user.avatar.url}}"
													class="rounded-circle img-responsive mt-2" width="128"
													height="128" />
												{% endif %}
												<h2 class="mt-3"> {{user.name}} </h2>
												<a href=" {% url 'staff:profile-update' pk=request.user.id %} "
													class="btn btn-primary mb-2">Update
													Profile</a>
												<a href="{% url 'account_change_password' %}"
													class="btn btn-primary mb-2">
													Update Password
												</a>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>
		{% include 'dashboard/footer.html' %}
	</div>
</div>


<script src=" {% static 'dashboard/js/app.js' %} "></script>

{% endblock content %}

templates/dashboard/sidebar.html
{% load static %}


<nav id="sidebar" class="sidebar">
    <div class="sidebar-content js-simplebar">
        <a class="sidebar-brand d-flex align-items-center" href=" {% url 'staff:dashboard' %} ">
            <img height="30" width="auto" src=" {% static 'icons/siusadatext-white.png' %} " alt="siusada">

        </a>

        <ul class="sidebar-nav">
            <li class="sidebar-header">
                Pages
            </li>

            <li class="sidebar-item {% if request.resolver_match.view_name == 'staff:dashboard' %}active{% endif %} ">
                <a class="sidebar-link" href=" {% url 'staff:dashboard' %} ">
                    <i class="align-middle" data-feather="grid"></i> <span class="align-middle">Dashboard</span>
                </a>
            </li>

            <li class="sidebar-item {% if request.resolver_match.view_name == 'staff:profile' %}active{% endif %} ">
                <a class="sidebar-link" href=" {% url 'staff:profile' %} ">
                    <i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
                </a>
            </li>

            <li class="sidebar-item {% if request.resolver_match.view_name == 'staff:products' %}active{% endif %} ">
                <a class="sidebar-link" href=" {% url 'staff:products' %} ">
                    <i class="align-middle" data-feather="shopping-bag"></i> <span class="align-middle">Products</span>
                </a>
            </li>

            <li class="sidebar-item {% if request.resolver_match.view_name == 'staff:order' %}active{% endif %}">
                <a class="sidebar-link" href=" {% url 'staff:order' %} ">
                    <i class="align-middle" data-feather="shopping-cart"></i> <span class="align-middle">Orders</span>
                </a>
            </li>

            <li
                class="sidebar-item {% if request.resolver_match.view_name == 'staff:confirmed-order' %}active{% endif %}">
                <a class="sidebar-link" href=" {% url 'staff:confirmed-order' %} ">
                    <i class="align-middle" data-feather="check-circle"></i> <span class="align-middle">Confirmed</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a class="sidebar-link" href=" {% url 'home' %} ">
                    <i class="align-middle" data-feather="globe"></i> <span class="align-middle">Go to homepage</span>
                </a>
            </li>

        </ul>
    </div>
</nav>